INSERT INTO sites
(url, login_name, account_email, tags, password, created_date, org_id)
VALUES
('http://www.quigley.com', 'alanna.kris@goyette.info', 'alanna.kris@goyette.info', 'work, home', 'password', '2019-11-30',1),
('http://www.bartell.org', 'alexandre50@gaylord.com', 'alexandre50@gaylord.com', 'entertainment', 'password', '2019-11-30',1),
('http://www.kutch.com', 'info@bogan.com', 'info@bogan.com', 'NULL', 'password', '2019-12-10',1),
('http://www.bauch.biz', 'marketing@jacobi.com', 'marketing@jacobi.com', 'NULL', 'password', '2019-12-26',1),
('http://www.wolff.biz', 'aaron63@swift.com', 'aaron63@swift.com', 'NULL', 'password', '2020-01-20',2),
('http://www.schneider.com', 'alfreda69@hotmail.com', 'alfreda69@hotmail.com', 'NULL', 'password', '2020-01-31',2),
('http://www.hirthe.com', 'info@crooks.com', 'info@crooks.com', 'NULL', 'password', '2020-02-01',2),
('http://www.macejkovic.com', 'marketing@keebler.com', 'marketing@keebler.com', 'NULL', 'password', '2020-02-03',2),
('http://www.poirier.net', 'alicia.quigley@fay.com', 'alicia.quigley@fay.com', 'NULL', 'password', '2020-02-06',3),
('http://www.berube.com', 'altenwerth.johanna@yahoo.com', 'altenwerth.johanna@yahoo.com', 'NULL', 'password', '2020-03-04',3),
('http://www.schaefer.com', 'info@doyle.info', 'info@doyle.info', 'NULL', 'password', '2020-03-13',3),
('http://www.johnson.net', 'marketing@gmail.com', 'marketing@gmail.com', 'NULL', 'password', '2020-03-25',3),
('http://www.ward.biz', 'marketing@gmail.com', 'marketing@gmail.com', 'NULL', 'password', '2020-03-27',3),
('http://www.veum.net', 'marketing@gmail.com', 'marketing@gmail.com', 'NULL', 'password', '2020-03-28',3),
('http://www.stracke.net', 'marketing@gmail.com', 'marketing@gmail.com', 'NULL', 'password', '2020-04-08',3),
('http://www.tremblay.info', 'marketing@gmail.com', 'marketing@gmail.com', 'work, home', 'password', '2020-04-26',3),
('http://www.giguere.com', 'marketing@gmail.com', 'marketing@gmail.com', 'work, home', 'password', '2020-05-06',3),
('http://www.paradis.com', 'marketing@gmail.com', 'marketing@gmail.com', 'work, home', 'password', '2020-05-09',3),
('http://www.mercier.com', 'marketing@gmail.com', 'marketing@gmail.com', 'NULL', 'password', '2020-05-19',3),
('http://www.padberg.com', 'marketing@koelpin.biz', 'marketing@koelpin.biz', 'NULL', 'password', '2020-07-17',3),
('http://www.waelchi.biz', 'info@feest.info', 'info@feest.info', 'NULL', 'password', '2020-08-20',4),
('http://www.schiller.com', 'marketing@halvorson.com', 'marketing@halvorson.com', 'NULL', 'password', '2020-09-03',4),
('http://www.little.net', 'marketing@hotmail.com', 'marketing@hotmail.com', 'NULL', 'password', '2020-10-01',4),
('http://www.dietrich.org', 'marketing@hotmail.com', 'marketing@hotmail.com', 'NULL', 'password', '2020-10-02',4),
('http://www.murphy.com', 'marketing@hotmail.com', 'marketing@hotmail.com', 'NULL', 'password', '2020-10-09',4),
('http://www.lepage.com', 'marketing@hotmail.com', 'marketing@hotmail.com', 'NULL', 'password', '2020-11-13',4),
('http://www.emard.com', 'marketing@marvin.com', 'marketing@marvin.com', 'NULL', 'password', '2019-11-30',4),
('http://www.larouche.net', 'americo51@corkery.com', 'americo51@corkery.com', 'NULL', 'password', '2019-11-30',5),
('http://www.rosenbaum.org', 'info@hirthe.com', 'info@hirthe.com', 'NULL', 'password', '2019-12-10',5),
('http://www.rolfson.com', 'marketing@fritsch.info', 'marketing@fritsch.info', 'NULL', 'password', '2019-12-26',5),
('http://www.gilbert.biz', 'marketing@fritsch.info', 'marketing@fritsch.info', 'NULL', 'password', '2020-01-20',5),
('http://www.durgan.com', 'durgan_marketing', 'marketing@gerlach.com', 'NULL', 'password', '2020-01-31',5),
('http://www.dibbert.biz', 'marketing@gleason.com', 'marketing@gleason.com', 'NULL', 'password', '2020-02-01',5),
('http://www.tremblay.net', 'marketing@mclaughlin.com', 'marketing@mclaughlin.com', 'NULL', 'password', '2020-02-03',5),
('http://www.rousseau.com', 'ashton80@carter.com', 'ashton80@carter.com', 'NULL', 'password', '2020-02-06',6),
('http://www.leffler.com', 'info@mckenzie.com', 'info@mckenzie.com', 'NULL', 'password', '2020-03-04',6),
('http://www.gagnon.biz', 'marketing@mclaughlin.com', 'marketing@mclaughlin.com', 'NULL', 'password', '2020-03-13',6),
('http://www.bradtke.com', 'asimonis@yahoo.com', 'asimonis@yahoo.com', 'NULL', 'password', '2020-03-25',7),
('http://www.goldner.com', 'info@schiller.biz', 'info@schiller.biz', 'NULL', 'password', '2020-03-27',7),
('http://www.hansen.biz', 'marketing@murray.com', 'marketing@murray.com', 'NULL', 'password', '2020-03-28',7),
('http://www.tessier.com', 'vince14@yahoo.com', 'vince14@yahoo.com', 'NULL', 'password', '2020-04-08',7),
('http://www.audet.com', 'bernita76@gmail.com', 'bernita76@gmail.com', 'NULL', 'password', '2020-04-26',8),
('http://www.couture.info', 'jacobs.elisha@hotmail.com', 'jacobs.elisha@hotmail.com', 'NULL', 'password', '2020-05-06',8),
('http://www.beaulieu.com', 'marketing@murray.com', 'marketing@murray.com', 'NULL', 'password', '2020-05-09',8),
('http://www.gravel.biz', 'wdicki@doyle.info', 'wdicki@doyle.info', 'NULL', 'password', '2020-05-19',8),
('http://www.desrosiers.com', 'bridget.lynch@schiller.biz', 'bridget.lynch@schiller.biz', 'NULL', 'password', '2020-07-17',9),
('http://www.dube.info', 'jessy.schoen@rath.net', 'jessy.schoen@rath.net', 'NULL', 'password', '2020-08-20',9),
('http://www.theriault.com', 'marketing@murray.com', 'marketing@murray.com', 'NULL', 'password', '2020-09-03',9),
('http://www.champagne.org', 'xmckenzie@bayer.com', 'xmckenzie@bayer.com', 'NULL', 'password', '2020-10-01',9),
('http://www.giguere.biz', 'gigeure_marketing', 'brown.mellie@robel.biz', 'NULL', 'password', '2020-10-02',10),
('http://www.bolduc.info', 'karen.stiedemann@gmail.com', 'karen.stiedemann@gmail.com', 'NULL', 'password', '2020-10-09',10),
('http://www.hills.com', 'marketing@murray.net', 'marketing@murray.net', 'NULL', 'password', '2020-11-13',10),
('http://www.therrien.biz', 'windler.elijah@hirthe.com', 'windler.elijah@hirthe.com', 'NULL', 'password', '2019-11-30',10),
('http://www.parker.net', 'cummerata.guiseppe@yahoo.com', 'cummerata.guiseppe@yahoo.com', 'NULL', 'password', '2019-11-30',11),
('http://www.schmitt.biz', 'kendall97@johns.biz', 'kendall97@johns.biz', 'NULL', 'password', '2019-12-10',11),
('http://www.emmerich.com', 'marketing@oberbrunner.com', 'marketing@oberbrunner.com', 'NULL', 'password', '2019-12-26',11),
('http://www.lemieux.com', 'Marketing_211321', 'daphne35@schiller.net', 'NULL', 'password', '2020-01-20',12),
('http://www.bins.com', 'khegmann@gmail.com', 'khegmann@gmail.com', 'NULL', 'password', '2020-01-31',12),
('http://www.harvey.com', 'marketing@oberbrunner.com', 'marketing@oberbrunner.com', 'NULL', 'password', '2020-02-01',12),
('http://www.bilodeau.com', 'darrell.cruickshank@champlin.com', 'darrell.cruickshank@champlin.com', 'NULL', 'password', '2020-02-03',13),
('http://www.richard.info', 'kohler.cooper@bernhard.biz', 'kohler.cooper@bernhard.biz', 'NULL', 'password', '2020-02-06',13),
('http://www.lynch.info', 'marketing@yahoo.com', 'marketing@yahoo.com', 'NULL', 'password', '2020-03-04',13),
('http://www.boivin.com', 'deangelo81@yahoo.com', 'deangelo81@yahoo.com', 'NULL', 'password', '2020-03-13',14),
('http://www.turcotte.net', 'krempel@bogan.com', 'krempel@bogan.com', 'NULL', 'password', '2020-03-25',14),
('http://www.reynolds.com', 'marketing@yundt.com', 'marketing@yundt.com', 'NULL', 'password', '2020-03-27',14),
('http://www.michaud.net', 'deonte.morar@hoppe.com', 'deonte.morar@hoppe.com', 'NULL', 'password', '2020-03-28',15),
('http://www.prosacco.com', 'lauretta75@prohaska.com', 'lauretta75@prohaska.com', 'NULL', 'password', '2020-04-08',15),
('http://www.desjardins.com', 'mdouglas@carter.com', 'mdouglas@carter.com', 'NULL', 'password', '2020-04-26',15),
('http://www.beaulieu.biz', 'srunolfsson@hotmail.com', 'srunolfsson@hotmail.com', 'NULL', 'password', '2020-05-06',15),
('http://www.brakus.com', 'dexter.predovic@crona.com', 'dexter.predovic@crona.com', 'NULL', 'password', '2020-05-09',16),
('http://www.okeefe.com', 'laverne57@yahoo.com', 'laverne57@yahoo.com', 'NULL', 'password', '2020-05-19',16),
('http://www.oreilly.com', 'mertz.andreane@hotmail.com', 'mertz.andreane@hotmail.com', 'NULL', 'password', '2020-07-17',16),
('http://www.poirier.biz', 'terrence.schulist@mante.net', 'terrence.schulist@mante.net', 'NULL', 'password', '2020-08-20',16),
('http://www.gosselin.com', 'dorothea70@hotmail.com', 'dorothea70@hotmail.com', 'NULL', 'password', '2020-09-03',17),
('http://www.fillion.org', 'lavonne22@mckenzie.com', 'lavonne22@mckenzie.com', 'NULL', 'password', '2020-10-01',17),
('http://www.harber.com', 'nbogan@jerde.com', 'nbogan@jerde.com', 'NULL', 'password', '2020-10-02',17),
('http://www.picard.com', 'frenner@white.biz', 'frenner@white.biz', 'nothing to see, work', 'password', '2020-10-09',18),
('http://www.lacroix.com', 'lester.wuckert@beer.com', 'lester.wuckert@beer.com', 'work', 'password', '2020-11-13',18),
('http://www.perreault.com', 'nels35@yahoo.com', 'nels35@yahoo.com', 'work', 'password', '2019-11-30',18),
('http://www.mercier.info', 'fritsch.garland@hotmail.com', 'fritsch.garland@hotmail.com', 'home', 'password', '2019-11-30',19),
('http://www.bouchard.com', 'lowe.waldo@yahoo.com', 'lowe.waldo@yahoo.com', 'entertainment', 'password', '2019-12-10',19),
('http://www.jean.net', 'niko68@gmail.com', 'niko68@gmail.com', 'business', 'password', '2019-12-26',19),
('http://www.paradis.com', 'grace45@bechtelar.org', 'grace45@bechtelar.org', 'business', 'password', '2020-01-20',20),
('http://www.champagne.com', 'ludie21@morar.info', 'ludie21@morar.info', 'work, business', 'password', '2020-01-31',20),
('http://www.harber.com', 'nitzsche.rowland@abbott.org', 'nitzsche.rowland@abbott.org', 'home', 'password', '2020-02-01',20),
('http://www.graham.biz', 'sdicki@bins.org', 'sdicki@bins.org', 'entertainment', 'password', '2020-02-03',20),
('http://www.bedard.com', 'sierra.gaylord@yahoo.com', 'sierra.gaylord@yahoo.com', 'tv', 'password', '2020-02-06',20),
('http://www.gilbert.com', 'skylar.zieme@gmail.com', 'skylar.zieme@gmail.com', 'tv', 'password', '2020-03-04',20),
('http://www.therrien.com', 'heaney.bridget@gulgowski.net', 'heaney.bridget@gulgowski.net', 'movies', 'password', '2020-03-13',21),
('http://www.davis.com', 'margarita.welch@gusikowski.com', 'margarita.welch@gusikowski.com', 'movies', 'password', '2020-03-25',21),
('http://www.gaudreault.com', 'nyasia.wilderman@rau.info', 'nyasia.wilderman@rau.info', 'games', 'password', '2020-03-27',21),
('http://www.batz.info', 'info@bayer.com', 'info@bayer.com', 'games', 'password', '2020-03-28',22),
('http://www.kihn.com', 'marketing@deckow.com', 'marketing@deckow.com', 'kids', 'password', '2020-04-08',22),
('http://www.labelle.com', 'rcrist@yahoo.com', 'rcrist@yahoo.com', 'kids', 'password', '2020-04-26',22),
('http://www.marvin.com', 'info@bechtelar.org', 'info@bechtelar.org', 'kids', 'password', '2020-05-06',23),
('http://www.leclerc.com', 'marketing@deckow.com', 'marketing@deckow.com', 'home', 'password', '2020-05-09',23),
('http://www.leblanc.com', 'rice.judah@yahoo.com', 'rice.judah@yahoo.com', 'home, kids', 'password', '2020-05-19',23),
('http://www.bruen.com', 'info@bernhard.biz', 'info@bernhard.biz', 'work', 'password', '2020-07-17',24),
('http://www.renaud.com', 'marketing@deckow.com', 'marketing@deckow.com', 'secret', 'password', '2020-08-20',24),
('http://www.luettgen.com', 'rocio44@gmail.com', 'rocio44@gmail.com', 'entertainment', 'password', '2020-09-03',24)
;
