DROP TABLE IF EXISTS sites CASCADE;

CREATE TABLE sites (
  id SERIAL PRIMARY KEY NOT NULL,
  url VARCHAR(255) NOT NULL,
  login_name VARCHAR(255) NOT NULL,
  account_email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  tags TEXT,

  created_date DATE NOT NULL DEFAULT NOW(),
  deleted_date DATE,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  org_id INTEGER REFERENCES organizations(id) ON DELETE CASCADE
);
