DROP TABLE IF EXISTS org_users CASCADE;

CREATE TABLE org_users (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  org_id INTEGER REFERENCES organizations(id) ON DELETE CASCADE,
  can_write BOOLEAN DEFAULT FALSE
);
